from sqlalchemy.ext.asyncio import AsyncSession

from src.core.redis import RedisClient
from src.engine.event_emitter import EVT_GAME_ERROR, EventEmitter
from src.engine.exceptions import RateLimitError
from src.engine.graph import build_graph, to_graph_state
from src.engine.nodes.endgame_node import endgame_node
from src.engine.nodes.init_node import init_node
from src.models import EpisodeConfig, EpisodeExport, Phase


class EpisodeRunner:
    """
    Orchestrates a full game episode through the LangGraph state machine:
    INIT → (LangGraph: SPEAKING → DELIBERATION → POLLING ↺) → VOTING → REACTION → ENDGAME.

    Usage:
        runner = EpisodeRunner(agents={...}, redis_client=client)
        export = await runner.run(config)
    """

    def __init__(self, agents: dict, redis_client: RedisClient) -> None:
        """
        Args:
            agents: Mapping of agent_id → agent instance. Must contain exactly 4 agents.
            redis_client: A live, connected RedisClient for event publishing.

        Raises:
            ValueError: if `agents` does not contain exactly 4 entries.
        """
        if len(agents) != 4:
            raise ValueError(
                f"EpisodeRunner requires exactly 4 agents, got {len(agents)}"
            )
        self._agents = agents
        self._redis_client = redis_client
        self._emitter: EventEmitter | None = None

    async def run(
        self, config: EpisodeConfig, db_session: AsyncSession
    ) -> EpisodeExport:
        """
        Runs a complete game episode. Calls each node in sequence.

        Emits events to Redis throughout the episode via self._emitter.
        Persists the completed EpisodeExport to PostgreSQL.

        Args:
            config: Full episode configuration including agent configs.
            db_session: AsyncSession for database persistence.

        Returns:
            Completed EpisodeExport with all action logs.

        Raises:
            EngineError: if the episode cannot complete for any reason.
        """
        # Set emitter when run starts
        self._emitter = EventEmitter(self._redis_client, config.episode_id)
        # Sequence 1: Init
        state = await init_node(config, self._emitter)

        # Inject the actual role assignments generated by init_node into the agents
        for agent_id, agent in self._agents.items():
            if hasattr(agent, "role_assignment"):
                agent.role_assignment = state.role_assignments[agent_id]

        # Sequence 2: LangGraph cyclical engine execution
        graph = build_graph(self._agents, self._emitter)
        graph_state = to_graph_state(state)
        try:
            final_graph_state = await graph.ainvoke(graph_state)
            state = final_graph_state["game_state"]
        except RateLimitError as exc:
            from src.core.quota import QuotaTracker

            await QuotaTracker.mark_exhausted(exc.provider)
            await self._emitter.emit(
                EVT_GAME_ERROR,
                {
                    "error_type": "rate_limit",
                    "provider": exc.provider,
                    "details": str(exc),
                    "error": f"Provider '{exc.provider}' is rate limited: {exc}",
                },
            )
            raise
        except Exception as exc:
            await self._emitter.emit(
                EVT_GAME_ERROR,
                {
                    "error_type": "unknown",
                    "provider": "unknown",
                    "details": str(exc),
                    "error": f"Engine execution crashed: {exc}",
                },
            )
            raise

        # Extract action logs from all agents
        action_logs = []
        for agent in self._agents.values():
            if hasattr(agent, "action_logs"):
                action_logs.extend(agent.action_logs)

        # Sequence 3: Endgame
        state.current_phase = Phase.ENDGAME
        return await endgame_node(state, action_logs, db_session, self._emitter)

    @property
    def emitter(self) -> EventEmitter | None:
        """
        Returns the EventEmitter for this episode runner,
        or None if run() has not started.
        """
        return self._emitter
